.babelrc
package.json
src/__tests__/ChartTests.js

This change introduces couple simple unit tests for `ChartComponent#shouldComponentUpdate()` function.
Tests written using using Jest unit testing framework. They mostly cover issue fixed in gor181/react-chartjs-2#17.

Basic unit tests for chart re-rendering

---

src/__tests__/ChartTests.js
src/utils/deepEqual.js

The current implementation of the `deepEquals` function only checks (recursively) if the second object has all the keys of the first object but doesn't check the other way around.
So if a key was added/removed from somewhere in the first object, this would not be considered a change.
Since that `shouldComponentUpdate` method calls `deepEquals` as follows:
`deepEqual(compareNext, compareNow)`
The effect is that if in the next props there was a change by adding/removing a key, the component won't rerender.
See issue #30 
Added a test for this case.

Fix for bug in deepEquals (Issue #30)

---

src/index.js

If you have a line chart that's data prop has a dataset value with a variable length of objects (eg a chart with a non-constant number of legend items), the original updateChart can only account for datasets that are growing in size, not shrinking. I added a quick check to the updateChart function that pops out the extraneous array values, if necessary. This saves you from having to call redraw over and over and can make your app run much smoother.

Keep legend length in sync with data length

---

package.json
test/config/setup.js
yarn.lock

Setting env vars like this `NODE_ENV=production` doesn't works on Windows.
Using `cross-env` fixes this issue: `cross-env NODE_ENV=production`
Note that I didn't update yarn.lock file because I'm not able to do a full install due to `canvas` dependency build failure

Use cross-env to enable windows build

---

.editorconfig
README.md
example/src/components/scatter.js
example/src/example.js
src/index.js

Chartjs has default config for scatter charts which are different than line charts in four key areas:
* x and y axis are both `linear`.
* hover mode is `single`.
* showLines is `false`.
* tooltip title doesn't make sense, as both x and y are both values.
Keeping in mind that this [default config](https://github.com/chartjs/Chart.js/blob/225bfd36f3daae2cfd0e2869658144ee6bfd988b/src/charts/Chart.Scatter.js) is already present within the base chartjs library, a different 'Scatter' chart should be exposed by this library - to avoid redundant configs to be written by each developer.
Also fixed the editorconfig - the whitespace strategy was not reflecting the code style.

Support 'scatter' charts out-of-the-box

---

src/index.js

If a user wants to use ChartComponent with an extended chart type, ChartComponent will currently spit out an error that the type field is invalid. With this change, we validate against the current chart types that have been added to chartjs. This includes the native chart types and any extended chart types.

Better PropType for type field

---

example/src/components/legend-handlers.js
example/src/components/legend-options.js
example/src/example.js
src/index.js
test/__tests__/Chart_spec.js

Legend object passed to options. See [legend docs](http://www.chartjs.org/docs/latest/configuration/legend.html)

Add legend support to charts

---

package.json
src/index.js
yarn.lock

closes #168 
Wasn't able to run tests due to issues with `canvas-prebuilt`.

use lodash.find instead of MDN polyfill

---

index.d.ts
package.json

- It looks like the current `index.d.ts` doesn't contain all of the interface props that ChartJS requires.
- Also, https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html defines the spec for types in package.json as:
```If your package has a main .js file, you will need to indicate the main declaration file in your package.json file as well. Set the types property to point to your bundled declaration file. For example:
{
"name": "awesome",
"author": "Vandelay Industries",
"version": "1.0.0",
"main": "./lib/main.js",
"types": "./lib/main.d.ts"
}
```

Update typings and package.json types as per latest Typescript specs

---

index.d.ts

The scatter chart was missing from the typescript declaration file
cheers,
Pete

add typings for scatter plot

---

package.json
src/index.js
yarn.lock

Most people use lodash and not `lodash.isequal` or `lodash.find`. They are custom builds of lodash, with a lot of duplicated code, and results in really heavy bundles.
Today I have to alias `lodash.find` to `lodash/find` and `lodash.isequal` to `lodash/isEqual` in my apps in order to prevent the duplicated code.
For reference, for [etalab/inspire](github.com/etalab/inspire), my output bundle is 5.88 KB (gzipped) heavier when I’m not aliasing lodash.find and lodash.isequal to their counterparts in lodash.
---
Before:
```
$ ll dist
total 392
-rw-r--r--  1 tusbar  staff   156K Aug 19 15:41 react-chartjs-2.js
-rw-r--r--  1 tusbar  staff    37K Aug 19 15:41 react-chartjs-2.min.js
```
After:
```
$ ll dist 
total 312
-rw-r--r--  1 tusbar  staff   124K Aug 19 15:40 react-chartjs-2.js
-rw-r--r-- …
```

Use real lodash instead of custom `lodash.*` builds

---

.storybook/webpack.config.js

- adds webpack alias for react-chartjs-2

fix for storybook cannot resolve module react-chartjs-2

---

package.json

- Pulls in a more stable and the latest version of Chart.js
- Fixes server side rendering (Fixed by Chart.js 2.6.0)

Bump Chart.js version to 2.6.0

---

LICENSE.md

Hi guys!
thanks for make this wrapper for chartjs!
At my job we have a strict policy about third-party software, so we are force to only use libraries with a explicit LICENSE file located in the repo's root. 
This PR just do one simple thing: Add the LICENSE file with the information found at `README.md`'s footer.
regards!

adding LICENSE file

---

src/index.js
stories/UpdatingChart.js
stories/index.js

This fixes #226 by maintaining the order of the nextDatasets while merging the data from currentDatasets.
Fixes #226

Improve update of datasets to use correct dataset order

---

index.d.ts

`plugins` and `datasetKeyProvider` were missing.

Added missing ChartComponent prop types

---

README.md
src/index.js

In order to operate on the `canvas` object directly, you should be able to assign an `id` attribute to it.

Added id prop to the canvas component

---

index.d.ts

- The lack of type for the argument breaks when TypeScript's `noImplicitAny` is enabled
- `datasetKeyProvider` is optional, as it defaults to `ChartComponent.getLabelAsKey`

Fix datasetKeyProvider typing

---

package.json
rollup.config.js
yarn.lock

Fixes UMD builds be injecting 'production' into where process.env.NODE_ENV exists. Should  
- https://github.com/jerairrest/react-chartjs-2/issues/277
- https://github.com/jerairrest/react-chartjs-2/issues/291
- https://github.com/jerairrest/react-chartjs-2/issues/277

Fix UMD build

---

README.md

Sample code in the README had not been updated to reflect the changes in https://github.com/jerairrest/react-chartjs-2/commit/edaa5dabee9a6f4f217df1e093141b353c9dc9b6.
The Chart.js instance reference key has changed from `chart_instance` to `chartInstance`.

Update sample code in README

---

src/index.js

This pull request fixes issue #324.

Fix issue #324: Re-using the same dataset in another chart (for example, in tabs) causes a failure.

---

README.md

Hi @jerairrest,
Thanks for your work with react-chartjs-2 👍 
This PR is perhaps a bit opinionated, but I think it improves the readability.

docs: improve code formatting in README.md

---

src/index.js

Fixes https://github.com/jerairrest/react-chartjs-2/issues/405
- Remove use of `componentWillMount` from `ChartComponent`
- Initialize chartInstance as null in the class constructor instead
```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-async-component-lifecycle-hooks for details.
* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
Please update the following components: **ChartComponent**
```

Remove componentWillMount (Deprecation warning in React 16.9)

---

example/src/components/pie.js

The label was "green" even though the color is blue.

Correct name of color in Pie.js

---

src/index.js

When using chartjs-plugin-streaming, the data in datasets is updated by a periodic call to onRefresh or similar function.
In that case, the recommended props to \<Line\> and other charts are datasets with no data property. This works fine until the Component is updated at which time there is a crash because data is not set.
This PR changed updateChart to check if data is present in the new props and only update if it is.

Bug fix: Make updateChart robust to missing data in dataset. 

---

index.d.ts

Typescript fix: sets the global `defaults` object type to match [what is specified in @types/chart.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/chart.js/index.d.ts#L47:L50), rather than an empty object.
Resolves #393

Allow global defaults to be set in Typescript without type errors

---

src/index.js

I've seen error this error in my logs:
```
TypeError: Unable to get property 'config' of undefined or null reference
at ChartComponent.prototype.destroyChart(/vendor.js:46065:21)
at ChartComponent.prototype.componentWillUnmount(/vendor.js:46001:21)
```
There might be a different issue, but this seems like a safe fix.

Prevent error in destroyChart when chartInstance does not exist

---

README.md

After having issues with the existing reference documentation in the README, I've updated it to the use the [createRef()](https://reactjs.org/docs/refs-and-the-dom.html) API.

Update ref syntax to the new React.createRef() API

---

rollup.config.js

Fixes [issue 509](https://github.com/jerairrest/react-chartjs-2/issues/509)
Uglify at some point moved the `options.compress.warnings` option to the top level, at `options.warnings`.
Because of this, on a fresh `npm i` you get a (transitive) version of uglify that no longer supports `options.compress.warnings` at all (I guess it was previously deprecated but working) so it breaks the build -- `npm run build` does not work.
This PR just moves that option to the correct location, and it works again.

Replace deprecated uglify options compress.warnings with warnings

---

index.d.ts

Allows the `id` prop to be used in TypeScript projects.
Without this a TypeScript error like the following is generated:
```
No overload matches this call.
Overload 1 of 2, '(props: Readonly<LinearComponentProps>): Line', gave the following error.
Type '{ id: string; data: ...; height: number; options: ... }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Line> & Readonly<LinearComponentProps> & Readonly<...>'.
Property 'id' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Line> & Readonly<LinearComponentProps> & Readonly<...>'.
Overload 2 of 2, '(props: LinearComponentProps, context?: any): Line', gave the following error.
Type '{ id: string; data: ...; height: number; options: ... }' is not assignable to type 'IntrinsicAttributes & …
```

Add the `id` prop to the TypeScript definitions.

---

README.md
package-lock.json
src/__tests__/chart.test.tsx
src/chart.tsx
src/types.ts

as per https://www.chartjs.org/docs/latest/general/accessibility.html
Relating to issue: #373
Solution is to allow any react node to be passed in as fallback content. This is to avoid overly coupling the feature with our specific use case. By default no change in output should be expected but the new prop object will allow passing in fallback content and an aria-label.
Set prop as an object to allow future expansion if other a11y best practices come about.

feat(a11y): support passing aria label and fallback

---

src/types.ts

`types.ts` was importing from JavaScript sources instead of TypeScript sources, causing WebStorm to treat props like `data` (`Chart.ChartData`) and `options` (`Chart.ChartOptions`) as `any` instead of the correct types.

Fix types.ts importing the wrong types

---

package-lock.json
src/__tests__/chart.test.tsx
src/types.ts

Current behavior fails with an error
Also, I saw a PR, which introduced this change. I propose a solution, which solves both webstorm and tsc issues

import Chart as namespace

---

src/index.tsx
stories/Chart.tsx
test/chart.test-d.tsx
test/chart.test.tsx

BREAKING CHANGE: default export is renamed to Chart

refactor: default export is renamed to Chart

---

.size-limit
src/chart.tsx
src/typedCharts.tsx
stories/Bar.tsx
stories/Bubble.tsx
stories/Chart.tsx
stories/Doughnut.tsx
stories/Line.tsx
stories/Pie.tsx
stories/PolarArea.tsx
stories/Radar.tsx
stories/Scatter.tsx
test/chart.test.tsx

Added support of tree-shaking of Chart.js
BREAKING CHANGE: Added support of tree-shaking of Chart.js. Now you should register Chart.js
components by youreslf.
#706

refactor: tree-shaking

---

src/chart.tsx
src/types.ts
test/chart.test.tsx

BREAKING CHANGE: Functional data prop is removed

refactor: functional data prop is removed

---

.size-limit
package.json
rollup.config.js

BREAKING CHANGE: New target browsers: ie 11 dropped for regular bundle, modern bundle builds for
browsers with es6 modules support.

refactor: new target browsers

---

src/chart.tsx
src/index.tsx
src/types.ts
src/utils.ts
stories/Chart.tsx
test/chart.test.tsx

BREAKING CHANGE: getDatasetAtEvent, getElementAtEvent and getElementsAtEvent props are removed,
utils with the same names can used instead

refactor: getDatasetAtEvent, getElementAtEvent and getElementsAtEvent props are removed

---

.size-limit
src/chart.tsx
src/types.ts
src/utils.ts
test/chart.test.tsx

datasetIdKey prop added to track datasets changes
#735 #814

feat: datasetIdKey prop

---

website/docusaurus.config.js

I've moved links from the footer to the top bar. Takes less place and looks nicer.

docs: remove footer in favor of the top bar

---

package.json
src/chart.tsx
src/types.ts
src/utils.ts
yarn.lock

fix: compatability with react 16 typings

---

src/chart.tsx
test/chart.test.tsx

Fixes #1054 
This extra code (and test) checks to make sure that the chart is properly redrawn when the type changes. 
Chart.JS does not support on-the-fly type updates, so a redraw is required.

feat: assure redraw occurs when type changes (#1054)

---

sandboxes/chart/multitype/App.tsx

Import and register `BarController` and `LineController` so the example works after build.
Fixes #1063.

fix: add BarController, LineController so multitype chart sample works after build

---

website/docs/faq/why-two.md

Was reading the docs and I think the question is more readable if it titled "why _does_ the package _have_" as opposed to "why the package has". Great project, thanks!

docs(faq): Update why-two question header
